---
theme: dark

server:
  address: tcp://0.0.0.0:9091/

log:
  level: info

identity_validation:
  reset_password:
    jwt_secret: ccd0ea311383be55387f78482a0bfb59f17df21d61ea97d42b3c62843871345e

totp:
  issuer: azru.uk
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: bcrypt
      bcrypt:
        cost: 12

access_control:
  default_policy: deny
  rules:
    - domain: azru.uk
      policy: bypass
    - domain:
        - jellyfin.azru.uk
        - jellyseerr.azru.uk
        - homeassistant.azru.uk
      policy: bypass
    - domain: "*.azru.uk"
      policy: one_factor

session:
  secret: ccd0ea311383be55387f78482a0bfb59f17df21d61ea97d42b3c62843871345d
  cookies:
    - name: authelia_session
      domain: azru.uk
      authelia_url: https://auth.azru.uk
      expiration: 12h
      inactivity: 30m
      remember_me: 7d

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 10m

storage:
  encryption_key: 6ca0597275e2a5a938d066510eae66c9766f53a657ecb0b87080b7a902d64b00
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
